# This is a basic workflow to help you get started with Actions

name: Java CI with Gradle

on:
  pull_request:
  
jobs:
  checkstyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Execute checkstyle to main
      run: ./gradlew checkstyleMain
    - name: Execute checkstyle to test
      run: ./gradlew checkstyleTest
